# Generated by Django 5.0 on 2023-12-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('uniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('deviceName', models.CharField(max_length=100)),
                ('deviceId', models.CharField(max_length=100)),
                ('serviceUUID', models.CharField(max_length=100)),
                ('txPower', models.CharField(max_length=100)),
                ('rssi', models.CharField(max_length=100)),
                ('timeLogged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
