# Generated by Django 5.0 on 2023-12-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='deviceManufacturer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
